# Copy this file to config.yaml and fill in your values
slack_webhook_url: "YOUR_SLACK_WEBHOOK_URL_HERE"  # required
newsapi_key: "YOUR_NEWSAPI_KEY_HERE"   # optional, leave blank to skip
google_news_lang: "en"
min_confidence: 0.8
min_severity: 0.6
since_days: 14
